### PR TITLE
Fix timeouts not being caught correctly

### LINKED ISSUE #14: Avoid AWS gateway timeouts
With the current implementation, we rely on the source interpreter to catch infinite recursions. This does work for non-trivial recursive processes, since the AWS lambda will timeout before the call stack reaches a large enough size to raise a MaximumStackLimitExceeded source error.

The consequence is that the entire grader process will return as a lambda timeout error. We then lose all the information (grades) of other grader programs in this process. So, if a single grader program results in an infinite recursion, then all the grader programs sent together with that program will not be able to return their marks.

To fix, use [`Promise.race()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/race) in the call to `runInContext`, using a second `Promise` that resolves with `setTimeout`.

### PR DESCRIPTION
**Pull request by ningyuansg**
Resolves #14.

@tuesmiddt There is a minor change in the response API from grader to backend. Namely, there is a new error type for timeouts, separate from runtime and syntax errors. The response is still an array of `Output`s, where an `Output` has [this type definition](https://github.com/source-academy/grader/blob/55bcc128a70b0f5e1ee07674fc7b195a62c11025/src/index.ts#L32). 

An example:
```JSON
[
    {
        "grade": 30,
        "resultType": "pass"
    },
    {
        "grade": 50,
        "resultType": "pass"
    },
    {
        "errors": [
            {
                "errorType": "syntax",
                "line": 28,
                "location": "student"
            },
            {
                "errorType": "syntax",
                "line": 32,
                "location": "student"
            }
        ],
        "resultType": "error"
    },
    {
        "errors": [
            {
                "errorType": "timeout"
            }
        ],
        "resultType": "error"
    }
]
```

### CODE REVIEW

File: src/index.ts [hunk 1]
```diff
@@ -1,6 +1,8 @@
-import { createContext, runInContext } from 'js-slang'
+import { createContext, runInContext, Result as SourceResult } from 'js-slang'
 import { SourceError } from 'js-slang/dist/types'
 
+const TIMEOUT_DURATION = process.env.NODE_ENV !== 'test' ? 20000 : 1000
```
Comment (tuesmiddt) [inline src/index.ts]: Prefer if this can be an env variable instead.

**Comment by tuesmiddt** [comment]
Looks good overall!

File: src/index.ts (hunk 1 above)
Comment (ningyuansg) [reply src/index.ts]: Fixed with 6d02b6a, but will need a complementary change in the terraform files of cadet to set this environment variable in the lambda node env. Will make this PR later.

**Comment by ningyuansg** [comment]
p.s. I forgot to update a JSDOC lemme fix that first
